[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_cmd = ["VimFilerTab", "VimFiler", "VimFilerExplorer"]

[[plugins]]
repo = 'mitsuhiko/vim-jinja'
on_ft = ["html"]

[[plugins]]
repo = "vim-scripts/python_fold"
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ["python", "python3", "djangohtml"]
insert = 1
