[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
  let g:Gtags_Auto_Update = 1
  let g:Gtags_Auto_Map = 0
  let g:Gtags_No_Auto_Jump = 1
  nmap <silent> <C-]> :<C-u>GtagsCursor<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'slim-template/vim-slim.git'

[[plugins]]
repo = 'cohama/lexima.vim'
