[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
set background=dark
let g:solarized_use16 = 1
" colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
" 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
au VimEnter * nested colorscheme solarized8_flat
au VimEnter * nested highlight CursorLine term=NONE cterm=NONE ctermbg=black
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
let g:Gtags_Auto_Update = 1
let g:Gtags_Auto_Map = 0
let g:Gtags_No_Auto_Jump = 1
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
nnoremap <silent> <C-]> :<C-u>DeniteCursorWord -buffer-name=gtags_completion gtags_completion<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'slim-template/vim-slim.git'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'himanoa/denite-git-grep'
hook_add = '''
nmap ;gg :<C-u>Denite git-grep:
'''
