[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent> [start]gd :<C-u>Gdiff<CR>
nnoremap <silent> [start]gb :<C-u>Gblame<CR>
nnoremap <silent> [start]gs :<C-u>Gstats<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
let g:Gtags_Auto_Update = 1
let g:Gtags_Auto_Map = 0
let g:Gtags_No_Auto_Jump = 1
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
nnoremap <silent> <C-]> :<C-u>DeniteCursorWord -buffer-name=gtags_completion gtags_completion<CR>
'''

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'himanoa/denite-git-grep'
hook_add = '''
nmap ;gg :<C-u>Denite git-grep:
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
let g:fern#default_hidden=1 " 隠しファイルを表示する
nnoremap <silent> [start]o :<C-u>Fern . -reveal=% -drawer<CR>
'''

[[plugins]]
repo = 'prettier/vim-prettier'
hook_post_update = '''
let g:dein#plugin.build = 'npm install'
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter' 

[[plugins]]
repo = 'iCyMind/NeoSolarized'
hook_add = '''
set background=light
au MyAutoCmd VimEnter * nested colorscheme NeoSolarized
'''

