[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'slim-template/vim-slim.git'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'vobornik/vim-mql4'

[[plugins]]
repo = 'fatih/vim-go'
