[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Lokaltog/powerline'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'slim-template/vim-slim.git'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'
