[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_cmd = ["VimFilerTab", "VimFiler", "VimFilerExplorer"]

[[plugins]]
repo = 'mitsuhiko/vim-jinja'
on_ft = ["html"]

[[plugins]]
repo = "vim-scripts/python_fold"
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ["python", "python3", "djangohtml"]
insert = 1

[[plugins]]
repo = 'vobornik/vim-mql4'
on_ft = ["mq", "mq4", "mql4"]

[[plugins]]
repo = 'jcf/vim-latex'
on_ft = ["tex"]
hook_source = '''
  if dein#util#_is_mac()
    set shellslash
    set grepprg=grep\ -nH\ $*
    let g:tex_flavor='latex'
    let g:Imap_UsePlaceHolders = 1
    let g:Imap_DeleteEmptyPlaceHolders = 1
    let g:Imap_StickyPlaceHolders = 0
    let g:Tex_DefaultTargetFormat = 'pdf'
    let g:Tex_IgnoredWarnings =
                \'LaTeX Font Warning:'."\n".
                \'Overfull'."\n".
                \'Underfull'
    let g:Tex_IgnoreLevel = 3
    let g:Tex_FormatDependency_pdf = 'dvi,pdf'
    let g:Tex_FormatDependency_ps = 'dvi,ps'
    let g:Tex_CompileRule_dvi = '/Library/TeX/texbin/platex -shell-escape
                \ -interaction=nonstopmode $*'
    let g:Tex_CompileRule_pdf = '/Library/TeX/texbin/dvipdfmx $*.dvi'
    let g:Tex_BibtexFlavor = '/Library/TeX/texbin/pbibtex'
    let g:Tex_ViewRule_dvi = '/usr/bin/open -a Preview'
    let g:Tex_ViewRule_pdf = '/usr/bin/open -a Preview'
  endif
'''
